version: '3'
services:
  app:
    container_name: "front-app"
    build:
      context: .
    tty: true
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
volumes:
    node_modules: